# EKF for Odometry (Continuous)
ekf_filter_node_odom:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    
    # For mixed reality, we primarily care about GPS position
    # Adjust these based on your vehicle's actual sensors
    odom0: /vehicle/wheel_odometry
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,  # vx, vy, vz
                   false, false, true,   # vroll, vpitch, vyaw
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    
    imu0: /vehicle/imu
    imu0_config: [false, false, false,
                  true,  true,  true,   # roll, pitch, yaw
                  false, false, false,
                  true,  true,  true,   # vroll, vpitch, vyaw
                  true,  true,  true]   # ax, ay, az
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: true

# EKF for Map (Includes GPS)
ekf_filter_node_map:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map
    
    # GPS-derived odometry from navsat_transform_node
    odom0: /odometry/gps
    odom0_config: [true,  true,  true,   # x, y, z
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    
    # Fused odometry from ekf_filter_node_odom
    odom1: /odometry/filtered
    odom1_config: [false, false, false,
                   false, false, false,
                   true,  true,  true,   # vx, vy, vz
                   false, false, false,
                   false, false, false]
    odom1_differential: false
    odom1_relative: false
    
    # IMU for orientation
    imu0: /vehicle/imu
    imu0_config: [false, false, false,
                  true,  true,  true,   # roll, pitch, yaw
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_differential: false
    imu0_relative: true